name: Mon Premier Workflow
 
on:
  push:
    branches:
      - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest
 
    steps:
      - name: Mon Job Simple
        run: echo "Mon premier workflow sur GitHub Actions"